### ISSUE TITLE
thanks for this driver!

### ISSUE THREAD

**Issue by BeauSlim** [notro/fbdbi#1]
I have an Adafruit OLED Bonnet (a 1.3" ssd1306 on i2c with a joystick and a couple buttons on gpio).  The ssd1307fb kernel driver works fine in text mode, but graphics from mplayer or the framebuffer version of Qt were  reversed left-to right in vertical stripes 8 pixels wide.  After hours of frustration trying to figure out what was wrong I decided to see if your driver would work even though it has been abandoned for years now.  Your driver was easy to understand, easy to tweak the tiny bit necessary, and it works like a charm.  So, thanks very much.  

Is that vertical reversing in the kernel driver the result of the "sys_imageblit and friends doesn't honour CONFIG_FB_CFB_REV_PIXELS_IN_BYTE" problem you mention in the source?

**Comment by notro** [comment]
ssd1307fb is a 1-bit per pixel monochrome driver:
```c
static const struct fb_fix_screeninfo ssd1307fb_fix = {
	.visual		= FB_VISUAL_MONO10,
```

Does mplayer support that format?

The driver in this repo can present itself as rgb565 and convert to monochrome internally.

I believe the rev pixels issue was some big/little endian problem, I don't remember the details.

**Comment by BeauSlim** [comment]
Yes, most things don't support mono, as you commented somewhere in this driver.  mplayer 1 does work.  mplayer2 does not.  X doesn't.  Qt5 "embedded"_does_ support mono if compiled for fbdev, which is how I knew that the vertical banding issue I saw wasn't just an mplayer issue.  

And, yes, the spoofing a color display is a piece of genius!  Your driver runs X on my OLED.  It's way too small to be useful, but still....  

Anyway, I realise this is an abandoned project.  I just wanted to say thanks for making it.
